Agent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from core import views

urlpatterns = [
    path("", views.LandingPageView.as_view(), name="home"),
    path("properties/", views.HouseIndexView.as_view(), name="properties"),
    path("contact_us/", views.ContactPageView.as_view(), name="contact-us"),
    path(
        "properties/<int:pk>/", views.HouseDetailView.as_view(), name="property-detail"
    ),
    path(
        "properties/<int:pk>/edit",
        views.HouseUpdateView.as_view(),
        name="property-edit",
    ),
    path(
        "properties/<int:pk>/images",
        views.ImageIndexView.as_view(),
        name="property-images",
    ),
    path("agents/", views.AgentIndexView.as_view(), name="agents"),
    path(
        "properties/add-property/", views.HouseCreateView.as_view(), name="add-property"
    ),
    path("agents/<int:pk>/", views.AgentDetailView.as_view(), name="agent-detail"),
    path("agents/<int:pk>/edit", views.AgentEditView.as_view(), name="agent-update"),

    # Auth
    path("login/", views.AgentLoginView.as_view(), name="login"),
    path("signup/", views.AgentSignUpView.as_view(), name="signup"),
    path("logout/", views.AgentLogoutView.as_view(), name="logout"),
    path("reset_password/", PasswordResetView.as_view(template_name="core/reset_password.html"), name="reset_password"),
    path("reset_password_confirm/<uidb64>/<token>/", PasswordResetConfirmView.as_view(template_name="core/reset_password_confirm.html"), name="password_reset_confirm"),
    path("reset_password_sent/", PasswordResetDoneView.as_view(template_name="core/reset_password_sent.html"), name="password_reset_done"),
    path("reset_password_complete/", PasswordResetCompleteView.as_view(template_name="core/reset_password_complete.html"), name="password_reset_complete"),

    # Ajax
    path("cities/", views.cities, name="cities"),
    path("delete_images/", views.delete_images, name="delete-image"),
    path("delete_house/", views.delete_house, name="delete-house"),
    path("delete_photo/", views.delete_photo, name="delete-photo"),

]

core/models.py
import os

from django.conf import settings
from django.contrib.auth.models import AbstractUser, User
from django.core.mail import send_mail
from django.core.validators import RegexValidator
from django.db import models
from django.shortcuts import reverse

from .managers import CustomUserManager


class User(AbstractUser):
    username = None
    photo_name = models.CharField(max_length=100, blank=True, null=True)
    photo_url = models.URLField(blank=True, null=True)
    phone_number = models.CharField(validators=[RegexValidator(
        regex=r"^\+?1?\d{9,15}$",
        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
    )], max_length=17, blank=True)
    email = models.EmailField(unique=True)
    twitter = models.CharField(max_length=500, null=True, blank=True)
    facebook = models.CharField(max_length=500, null=True, blank=True)
    instagram = models.CharField(max_length=500, null=True, blank=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    objects = CustomUserManager()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Region(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class City(models.Model):
    name = models.CharField(max_length=100)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "cities"

    def __str__(self):
        return self.name

class House(models.Model):
    agent = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField()
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    address = models.CharField(max_length=500)
    price = models.PositiveIntegerField()
    forsale = models.BooleanField(default=True)
    rooms = models.PositiveIntegerField(default=0)
    garages = models.PositiveIntegerField(default=0)
    sitting_rooms = models.PositiveIntegerField(default=0)
    dining_rooms = models.PositiveIntegerField(default=0)
    bathrooms = models.PositiveIntegerField(default=1)
    kitchen = models.PositiveIntegerField(default=1)
    year_built = models.CharField(max_length=5)
    added_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"House {self.id}"

    def get_absolute_url(self):
        return reverse("property-detail", args=(self.pk,))


class Image(models.Model):
    name = models.CharField(max_length=100)
    house = models.ForeignKey(House, on_delete=models.CASCADE)
    url = models.URLField()

    def __str__(self):
        return f"House {self.house.id} images"


class Message(models.Model):
    agent = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField(max_length=100)
    message = models.TextField()

    def __str__(self):
        return f"Message from {self.email} for agent @ {self.agent.email}" if self.agent else f"Message from {self.email}"

core/forms.py
import datetime
import re
from django import forms
from django.contrib.auth import get_user_model, authenticate, password_validation
from django.contrib.auth.forms import (
    UserChangeForm,
    UserCreationForm,
    AuthenticationForm,
)
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.utils.translation import gettext_lazy as _

from .models import (
    House, 
    Image, 
    Message,
    Region,
    City
    )

User = get_user_model()


def year_choices():
    year_choices = [("older", "older"), ("1800s", "1800s"), ("1900s", "1900s")]
    year_choices.extend(
        [(str(x), str(x)) for x in range(2000, datetime.date.today().year + 1)]
    )
    return year_choices


class LoginForm(AuthenticationForm):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "autofocus": True,
                "class": "text-slate-900 text-sm rounded-md w-full p-2 outline-none focus:border-2 focus:border-indigo-600 placeholer-opacity-0.5 placeholder:italic placeholder:text-sm placeholder:opacity-70",
            }
        )
    )

    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "current-password",
                "class": "text-slate-900 text-sm rounded-md w-full p-2 outline-none focus:border-2 focus:border-indigo-600 placeholer-opacity-0.5 placeholder:italic placeholder:text-sm placeholder:opacity-70",
            }
        ),
    )

    remember_me = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                "class": "w-4 h-4 border-2 border-indigo-600 rounded",
            }
        ),
    )
    username = None

    error_messages = {
        "invalid_login": _(
            "Please enter a correct email and password. Note that both "
            "fields may be case-sensitive."
        ),
        "inactive": _("This account is inactive."),
    }

    def __init__(self, request=None, *args, **kwargs):
        """
        The 'request' parameter is set for custom auth use by subclasses.
        The form data comes in via the standard 'data' kwarg.
        """
        self.request = request
        self.user_cache = None
        forms.Form.__init__(self, *args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email is not None and password:
            self.user_cache = authenticate(self.request, email=email, password=password)
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def get_invalid_login_error(self):
        return ValidationError(
            self.error_messages["invalid_login"],
            code="invalid_login"
        )


class AdminUserCreationForm(UserCreationForm):
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                "class": " text-slate-900 text-sm rounded-md w-full p-2 outline-none focus:border-2 focus:border-indigo-600 placeholer-opacity-0.5 placeholder:italic placeholder:text-sm placeholder:opacity-70",
            }
        ),
        help_text=password_validation.password_validators_help_text_html(),
    )

    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                "class": " text-slate-900 text-sm rounded-md w-full p-2 outline-none focus:border-2 focus:border-indigo-600 placeholer-opacity-0.5 placeholder:italic placeholder:text-sm placeholder:opacity-70",
            }
        ),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    phone_number = forms.CharField(
        max_length=15,
        widget=forms.TextInput(
                    attrs={
                        "class": "text-slate-900 text-sm rounded-md w-full p-2 outline-none focus:border-2 focus:border-indigo-600 placeholer-opacity-0.5 placeholder:italic placeholder:text-sm placeholder:opacity-70",
                        }
                    ),
        validators=[
            RegexValidator(
                regex=r"^\+?1?\d{9,15}$", 
                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits is allowed.",
                )
            ]
        )
    
    photo = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = [
            "email",
            "first_name",
            "last_name",
            "phone_number",
            "photo",
            "password1",
            "password2",
            "twitter",
            "instagram",
            "facebook",
            "is_staff",
            "is_active",
        ]

        widgets = {
            "email": forms.EmailInput(
                attrs={
                    "class": " text-slate-900 text-sm rounded-md w-full  p-2 outline-none focus:border-2 focus:border-indigo-600 placeholer-opacity-0.5 placeholder:italic placeholder:text-sm placeholder:opacity-70",
                }
            ),
            "first_name": forms.TextInput(
                attrs={
                    "class": " text-slate-900 text-sm rounded-md w-full  p-2 outline-none focus:border-2 focus:border-indigo-600 placeholer-opacity-0.5 placeholder:italic placeholder:text-sm placeholder:opacity-70",
                }
            ),
            "last_name": forms.TextInput(
                attrs={
                    "class": " text-slate-900 text-sm rounded-md w-full  p-2 outline-none focus:border-2 focus:border-indigo-600 placeholer-opacity-0.5 placeholder:italic placeholder:text-sm placeholder:opacity-70",
                }
            ),
            "twitter": forms.TextInput(
                attrs={
                    "class": " text-slate-900 text-sm rounded-md w-full  p-2 outline-none focus:border-2 focus:border-indigo-600 placeholer-opacity-0.5 placeholder:italic placeholder:text-sm placeholder:opacity-70",
                }
            ),
            "instagram": forms.TextInput(
                attrs={
                    "class": " text-slate-900 text-sm rounded-md w-full  p-2 outline-none focus:border-2 focus:border-indigo-600 placeholer-opacity-0.5 placeholder:italic placeholder:text-sm placeholder:opacity-70",
                }
            ),
            "facebook": forms.TextInput(
                attrs={
                    "class": " text-slate-900 text-sm rounded-md w-full  p-2 outline-none focus:border-2 focus:border-indigo-600 placeholer-opacity-0.5 placeholder:italic placeholder:text-sm placeholder:opacity-70",
                }
            ),
            "is_staff": forms.CheckboxInput(
                attrs={
                    "class": "rounded-full px-1 mb-2 form-check-input appearance-none h-4 w-4 border border-gray-300 bg-white checked:bg-indigo-500 checked:border-indigo-500 transition duration-200 mt-1 align-top bg-no-repeat bg-center bg-contain cursor-pointer"
                }),
            "is_active": forms.CheckboxInput(
                attrs={
                    "class": "rounded-full px-1 mb-2 form-check-input appearance-none h-4 w-4 border border-gray-300 bg-white checked:bg-indigo-500 checked:border-indigo-500 transition duration-200 mt-1 align-top bg-no-repeat bg-center bg-contain cursor-pointer"
                })
        }


class CustomUserCreationForm(AdminUserCreationForm):

    class Meta:
        model = User
        fields = AdminUserCreationForm.Meta.fields
        fields.remove("is_staff")
        fields.remove("is_active")

        widgets = AdminUserCreationForm.Meta.widgets
        widgets.pop("is_staff")
        widgets.pop("is_active")


class AdminUserChangeForm(UserChangeForm):

    phone_number = forms.CharField(
        max_length=15,
        widget=forms.TextInput(
                    attrs={
                        "class": "text-slate-900 text-sm rounded-md w-full p-2 outline-none focus:border-2 focus:border-indigo-600 placeholer-opacity-0.5 placeholder:italic placeholder:text-sm placeholder:opacity-70",
                        }
                    ),
        validators=[
            RegexValidator(
                regex=r"^\+?1?\d{9,15}$", 
                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits is allowed.",
                )
            ]
        )

    photo = forms.ImageField(required=False)
    class Meta:
        model = User
        fields = (
            "email",
            "first_name",
            "last_name",
            "phone_number",
            "photo",
            "twitter",
            "instagram",
            "facebook",
            "is_staff",
            "is_active",
            "password"
        )

        widgets = AdminUserCreationForm.Meta.widgets


class CustomUserChangeForm(AdminUserChangeForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "phone_number",
            "twitter",
            "instagram",
            "facebook",
        )
        widgets = CustomUserCreationForm.Meta.widgets
        widgets.pop("email")
        

class HouseFilterForm(forms.ModelForm):
    class Meta:

        model = House
        fields = (
            "city",
            "region",
            "rooms",
            "forsale",
            "price",
            "garages",
            "sitting_rooms",
            "dining_rooms",
            "kitchen",
            "bathrooms",
        )

        widgets = {

templates/core/agent-update.html
{% extends "core/base.html" %} {% block content %}
<div class="flex justify-end mr-12 mt-4">
    <a class="underline text-red-500" href="{% url 'reset_password' %}">Reset password</a>
</div>
<section class="py-4 px-4 mx-4 my-12 md:mx-12 md:p-8 lg:p-24  lg:mx-48 rounded-md bg-slate-800">
    <h1 class="sm:text-3xl text-2xl title-font mb-8 text-indigo-600 text-xl font-medium leading-tight tracking-tight">
        Edit your profile
    </h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="grid grid-cols-2 gap-x-2 mb-2">
            <div class="">
                <label class="block mb-2 font-medium text-slate-400" for="id_first_name">First name</label>
                {{ form.first_name }}
                {% if form.first_name.errors %}
                {% for error in form.first_name.errors %}
                <p class="text-red-500 text-sm">{{ error }}</p>
                {% endfor %}
                {% endif %}
            </div>
            <div class="">
                <label class="block mb-2 font-medium text-slate-400" for="id_last_name">Last name</label>
                {{ form.last_name }} 
                {% if form.last_name.errors %}
                {% for error in form.last_name.errors %}
                <p class="text-red-500 text-sm">{{ error }}</p>
                {% endfor %}
                {% endif %}
            </div>
        </div>

        <div class="mb-2">
            <label class="block mb-2 font-medium text-slate-400" for="id_photo">Photo</label>
            <input type="file" name="photo" id="id_photo" />

            {% if form.instance.photo_url %}
            <div id="photo_div" class="mt-2">
                <a class="text-indigo-600 underline mr-4" href="{{ form.instance.photo_url }}">View Profile Pic</a>
                <span id="remove_photo" data-agent-id="{{ form.instance.id }}"
                    class="text-red-500 underline cursor-pointer">Remove</span>
            </div>
            {% endif %}
        </div>
        <div class="mb-2">
            <label class="block mb-2 font-medium text-slate-400" for="id_phone_number">Phone number</label>
            {{ form.phone_number }}
        </div>
        <input
            class="bg-indigo-600 text-slate-900 rounded-md w-full mt-4 py-2 font-semibold border-2 border-indigo-600 hover:text-indigo-600 hover:bg-transparent"
            type="submit" value="Submit" />
    </form>
</section>

{% endblock %} {% block js %}
<script>
    const remove = document.getElementById("remove_photo");
    const csrftoken = getCookie("csrftoken");

    function getCookie (name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== "") {
            const cookies = document.cookie.split(";");
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === name + "=") {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    remove.addEventListener("click", (e) => {
        const data = { agent_id: e.target.dataset.agentId };
        fetch("{% url 'delete-photo' %}", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "X-CSRFToken": csrftoken,
            },
            body: JSON.stringify(data),
        })
            .then((res) => res.json())
            .then((data) => {
                if (data.delete) {
                    const photo_div = document.getElementById("photo_div");
                    photo_div.remove();
                }
            })
            .catch((err) => {
                console.log(err);
            });
    });
</script>
{% endblock %}

templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <style>
      :root {
        --slate-900: #0f172a;
        --slate-400: #94a3b8;
        --indigo-600: #4f46e5;
      }

      input[type="text"],
      input[type="password"],
      input[type="email"],
      input[type="url"],
      input[type="number"],
      input[type="tel"],
      textarea,
      select,
      .VtextField {
        color: var(--slate-400);
        background-color: var(--slate-900);
      }

      .rotate {
        transform: rotate(270deg);
      }

      .wrap {
        flex-wrap: wrap;
        row-gap: 0.5rem;
      }

      @media only screen and (min-width: 768px) {
        .rotate {
          transform: rotate(180deg);
        }

        .wrap {
          flex-wrap: nowrap;
          row-gap: 0;
        }
      }
    </style>
    {% block morestyle %} {% endblock %}
    <title>Agency</title>
  </head>

  <body class="bg-slate-900 text-slate-300 font-sans">
    <nav class="bg-slate-800 py-3 md:px-12 px-2">
      <div id="menu" class="relative">
        <svg
          fill="currentColor"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 50 50"
          class="absolute ml-8 sm:hidden w-4 h-4 text-indigo-800"
        >
          <path
            d="M 5 8 A 2.0002 2.0002 0 1 0 5 12 L 45 12 A 2.0002 2.0002 0 1 0 45 8 L 5 8 z M 5 23 A 2.0002 2.0002 0 1 0 5 27 L 45 27 A 2.0002 2.0002 0 1 0 45 23 L 5 23 z M 5 38 A 2.0002 2.0002 0 1 0 5 42 L 45 42 A 2.0002 2.0002 0 1 0 45 38 L 5 38 z"
          />
        </svg>
      </div>
      <div class="md:flex md:flex-row flex-col md:justify-between">
        <div class="text-center">
          <a
            href="{% url 'home' %}"
            class="text-indigo-600 font-semibold sm:text-2xl font-serif"
          >
            Homes
          </a>
        </div>
        <div class="flex justify-between w-full md:ml-6">
          <div class="flex items-center md:gap-x-2 gap-x-1">
            <a
              class="text-slate-400 md:text-base text-sm leading-tight md:leading-normal font-medium hover:text-indigo-600"
              href="{% url 'properties' %}"
              >Properties</a
            >
            <a
              class="text-slate-400 md:text-base text-sm leading-tight md:leading-normal font-medium hover:text-indigo-600"
              href="{% url 'agents' %}"
              >Our Agents</a
            >
            <a
              class="text-slate-400 md:text-base text-sm leading-tight md:leading-normal font-medium hover:text-indigo-600"
              href="{% url 'contact-us' %}"
              >Contact Us</a
            >
          </div>
          {% if request.user.is_authenticated %}
          <a
            href="{% url 'agent-detail' request.user.id %}"
            class="sm:ml-0 ml-1 text-indigo-600 break-all italic sm:text-base text-xs"
          >
            {{ request.user.email }}</a
          >
          {% else %}
          <div class="flex gap-x-1 md:gap-x-2 items-center">
            <a
              href="{% url 'login' %}"
              class="md:text-base text-xs font-semibold hover:text-indigo-600"
              >Sign-in</a
            >
            <div
              class="bg-indigo-600 text-slate-900 md:text-base text-xs font-semibold border-2 border-indigo-600 hover:text-indigo-600 hover:bg-slate-900 rounded-md md:px-3 px-2 py-1"
            >
              <a href="{% url 'signup' %}" class="">Sign-up</a>
            </div>
          </div>
          {% endif %}
        </div>
      </div>
    </nav>
    {% block content %} {% endblock %} {% include 'core/footer.html' %}
    <script>
      const data_href = window.location.href.endsWith("properties/");
      let menu = document.getElementById("menu");
      let filter = document.getElementById("filter");

      function showFilter() {
        if (data_href) {
          if (screen.width <= 425) {
            menu.addEventListener("click", (e) => {
              let display = filter.style.display;
              if (display == "none") {
                filter.style.display = "block";
              } else {
                filter.style.display = "none";
              }
            });
          }
        }
      }

      showFilter();

      window.addEventListener("resize", () => {
        if (data_href && screen.width >= 768) {
          filter.style.display = "block";
        }
      });

      if (data_href && screen.width >= 768) {
        filter.style.display = "block";
      }
    </script>
    {% block js %} {% endblock %}
  </body>
</html>

templates/core/reset_password.html
{% extends "core/base.html" %}

{% block morestyle %}
<style>
    input[type=email] {
        border-radius: 0.375rem;
        color: var(--slate-400);
        background-color: var(--slate-900);
        margin-top: 0.25rem;
        outline: 2px solid transparent;
        outline-offset: 2;
        height: 2rem;
        padding-left: 0.5rem;
        padding-right: 0.5rem;
        font-size: 1rem;
        line-height: 1.5rem;
    }

    input[type=email]:focus {
        border-width: 2px;
        border-color: var(--indigo-600);
    }
</style>

{% endblock %}

{% block content %}
<main class="h-screen">
    <section class="lg:mx-48 sm:mx-32  my-12 bg-slate-800 rounded-md sm:p-12 p-8">
        <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-indigo-600">Password reset</h1>
        <h2 class="mb-2">Forgotten your password? Enter your email address below, if the email exists we’ll email
            instructions for setting a new one.
        </h2>
        <form action="." method="post">
            {% csrf_token %}
            <div class="my-4">
                <label class="font-medium mr-2" for="id_email">Email</label>
                {{ form.email }}
            </div>
            <input
                class="bg-indigo-600 text-slate-900 rounded-md w-full mt-4 py-2 font-semibold border-2 border-indigo-600 hover:text-indigo-600 hover:bg-transparent flex mx-auto justify-center text-lg"
                type="submit" value="Reset Password ">
        </form>
    </section>

</main>

{% endblock %}

templates/core/signup.html
{% extends "core/base.html" %}
{% block content %}
<section class="py-4 px-4 mx-4 my-12 md:mx-12 md:p-8 lg:p-24  lg:mx-48 rounded-md bg-slate-800">
    <h1 class="sm:text-3xl text-2xl title-font mb-8 text-indigo-600 text-xl font-medium leading-tight tracking-tight">
        Sign Up</h1>
    <form action="." method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-2">
            <label class="block mb-2 font-medium text-slate-400" for="id_email">Email</label>
            {{ form.email }}
            {% if form.email.errors %}
            {% for error in form.email.errors %}
            <p class="text-red-500 text-sm">{{ error }}</p>
            {% endfor %}
            {% endif %}
        </div>
        <div class="grid grid-cols-2 gap-x-2 mb-2">
            <div class="">
                <label class="block mb-2 font-medium text-slate-400" for="id_first_name">First name</label>
                {{ form.first_name }}
                {% if form.first_name.errors %}
                {% for error in form.first_name.errors %}
                <p class="text-red-500 text-sm">{{ error }}</p>
                {% endfor %}
                {% endif %}
            </div>
            <div class="">
                <label class="block mb-2 font-medium text-slate-400" for="id_last_name">Last name</label>
                {{ form.last_name }}
                {% if form.last_name.errors %}
                {% for error in form.last_name.errors %}
                <p class="text-red-500 text-sm">{{ error }}</p>
                {% endfor %}
                {% endif %}
            </div>
        </div>

        <div class="mb-2">
            <label class="block mb-2 font-medium text-slate-400" for="id_photo">Photo</label>
            <input type="file" name="photo" id="id_photo" required>
        </div>
        <div class="mb-2">

            <label class="block mb-2 font-medium text-slate-400" for="id_phone_number">Phone number</label>
            {{ form.phone_number }}
            {% if form.phone_number.errors %}
            {% for error in form.phone_number.errors %}
            <p class="text-red-500 text-sm">{{ error }}</p>
            {% endfor %}
            {% endif %}
        </div>
        <div class="mb-2">
            <label class="block mb-2 font-medium text-slate-400" for="id_password1">Password</label>
            {{ form.password1 }}
            {% if form.password1.errors %}
            {% for error in form.password1.errors %}
            <p class="text-red-500 text-sm">{{ error }}</p>
            {% endfor %}
            {% endif %}
        </div>
        <div class="mb-2">
            <label class="block mb-2 font-medium text-slate-400" for="id_password2">Password confirmation</label>
            {{ form.password2 }}
            {% if form.password2.errors %}
            {% for error in form.password2.errors %}
            <p class="text-red-500 text-sm">{{ error }}</p>
            {% endfor %}
            {% endif %}
        </div>

        <input
            class="bg-indigo-600 text-slate-900 rounded-md w-full mt-4 py-2 font-semibold border-2 border-indigo-600 hover:text-indigo-600 hover:bg-transparent"
            type="submit" value="Sign-up">
    </form>
    <p class="mt-8 text-sm font-light text-slate-400">
        Do you have an account yet? <a href="{% url 'login' %}" class="font-medium text-slate-400 hover:underline">Log in</a>
    </p>
</section>

{% endblock %}